"""
Constantes globais do jogo Plane Free
"""

# Configurações de Tela
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FPS = 60

# Cores (RGB)
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 100, 255)
COLOR_YELLOW = (255, 255, 0)
COLOR_GRAY = (128, 128, 128)

# Área jogável (com margem)
PLAY_AREA_MARGIN = 50
PLAY_AREA_LEFT = PLAY_AREA_MARGIN
PLAY_AREA_RIGHT = SCREEN_WIDTH - PLAY_AREA_MARGIN
PLAY_AREA_TOP = PLAY_AREA_MARGIN
PLAY_AREA_BOTTOM = SCREEN_HEIGHT - PLAY_AREA_MARGIN

# Versão do jogo
GAME_VERSION = "0.1.0-sprint1"  # ← ATUALIZADO
GAME_TITLE = "Plane Free"